apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: srip-coordinator
  annotations:
spec:
  template:
    metadata:
      labels:
        app: coordinator
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
        - image: ghcr.io/naveen-pal/srip-coordinator:latest
          envFrom:
            - secretRef:
                name: srip-secrets
          ports:
            - containerPort: 5000
      imagePullSecrets:
        - name: ghcr-secret 