# knative/prospective_intern/service.yaml
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: prospective_intern-service
spec:
  template:
    spec:
      containers:
        - image: ghcr.io/your-org/srip-prospective_intern:latest
          env:
            - name: FLASK_ENV
              value: "production"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: srip-secrets
                  key: database-url
          ports:
            - containerPort: 5000