apiVersion: networking.internal.knative.dev/v1alpha1
kind: Ingress
metadata:
  name: srip-ingress
  namespace: default
spec:
  rules:
    - hosts:
        - srip.example.com
      http:
        paths:
          - path: /
            splits:
              - percent: 100
                serviceName: srip-home
                serviceNamespace: default
                servicePort: 80
          - path: /auth
            splits:
              - percent: 100
                serviceName: srip-auth
                serviceNamespace: default
                servicePort: 80
          - path: /coordinator
            splits:
              - percent: 100
                serviceName: srip-coordinator
                serviceNamespace: default
                servicePort: 80
          - path: /faculty
            splits:
              - percent: 100
                serviceName: srip-faculty
                serviceNamespace: default
                servicePort: 80
          - path: /selected_intern
            splits:
              - percent: 100
                serviceName: srip-selected-intern
                serviceNamespace: default
                servicePort: 80
          - path: /prospective_intern
            splits:
              - percent: 100
                serviceName: srip-prospective-intern
                serviceNamespace: default
                servicePort: 80
