# knative/knative-routes.yaml
apiVersion: networking.knative.dev/v1
kind: Ingress
metadata:
  name: srip-ingress
spec:
  rules:
    - hosts:
        - srip.example.com
      http:
        paths:
          - path: /
            splits:
              - serviceName: srip-home
                percent: 100
          - path: /auth
            splits:
              - serviceName: srip-auth
                percent: 100
          - path: /coordinator
            splits:
              - serviceName: srip-coordinator
                percent: 100
          - path: /faculty
            splits:
              - serviceName: srip-faculty
                percent: 100
          - path: /selected_intern
            splits:
              - serviceName: srip-selected-intern
                percent: 100
          - path: /prospective_intern
            splits:
              - serviceName: srip-prospective-intern
                percent: 100