apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: srip-auth
  annotations:
    networking.knative.dev/ingress.class: istio.ingress.networking.knative.dev
spec:
  template:
    metadata:
      labels:
        app: auth
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
        - image: ghcr.io/naveen-pal/srip-auth:latest
          envFrom:
            - secretRef:
                name: srip-secrets
          ports:
            - containerPort: 5000
      imagePullSecrets:
        - name: ghcr-secret 